
class IScanData_FC
{
public:
	enum EFunctionCode_IScanData
	{
		FC_GETSCANINFO = 0 ,
		FC_GETSCANOPTION,
		FC_SETSCANOPTION,
		FC_STORESCANOPTION,
		FC_SETHOMINGCHANNEL,
		FC_GETHOMINGCHANNEL,
		FC_GETHOMINGCHANNELCANDIDATES,
		FC_RESETHOMINGCHANNEL,
		FC_SETPREFERREDTARGETREGION,
		FC_GETPREFERREDTARGETREGION,
		FC_SETCAMOPERATORPROFILESCANACTIVE,
		FC_SETAPPSCANACTIVE,
		FC_CHECKSERVICELISTSREGISTERED,
		FC_GETNETWORKS,
		FC_SETPREFERREDNETWORK,
		FC_DELETENETWORKS,
		FC_GETSERVICELISTS,
		FC_SETSERVICELIST,
		FC_GETSERVICESFORREPLACEMENT,
		FC_CHECKSERVICESFORREPLACEMENT,
		FC_CHECKSCANACTIVE,
		FC_CHECKMANUALSCANPERFORMED,
		FC_GETTARGETSUBREGIONS,
		FC_GETINTERACTIVESTORAGEALLOCATIONS,
		FC_SETPOSTCODE,
		FC_GETPOSTCODE,
		FC_VERIFYPOSTCODE,
		FC_CHECKMISSINGTRANSPONDERSFOUND,
		FC_GETCOLORSYSTEM,
		FC_SETCOLORSYSTEM,
		FC_GETSOUNDSYSTEM,
		FC_SETSOUNDSYSTEM,
		FC_GETREGIONALSERVICELISTS,
		FC_SETREGIONALSERVICELIST,
	};
};

