
class ITunerControl_FC
{
public:
	enum EFunctionCode_ITunerControl
	{
		FC_GETSIGNALSTRENGTH = 0 ,
		FC_GETSIGNALQUALITY,
		FC_GETSNR,
		FC_RESETMFT,
		FC_TUNEFORMFT,
		FC_SAVEFORMFT,
		FC_GETTUNEROFFSETFORMFT,
		FC_GETBER,
		FC_GETSIGNALKIND,
		FC_GETTUNERINDEX,
		FC_GETTUNESIGNALSTATE,
	};
};

