
class ISatellite_FC
{
public:
	enum EFunctionCode_ISatellite
	{
		FC_FINDSATELLITELIST = 0 ,
		FC_FINDSATELLITE,
		FC_SETSATELLITEPOSITION,
		FC_FINDTRANSPONDERLIST,
		FC_FINDTRANSPONDER,
		FC_ADDUSERTRANSPONDER,
		FC_REMOVEUSERTRANSPONDER,
		FC_RESET,
		FC_CHECKDBUPDATED,
		FC_CONFIRMDBUPDATE,
	};
};

