
class IScanControl_FC
{
public:
	enum EFunctionCode_IScanControl
	{
		FC_STARTAUTOSCAN = 0 ,
		FC_STOPAUTOSCAN,
		FC_PAUSEAUTOSCAN,
		FC_RESUMEAUTOSCAN,
		FC_ACTIVATEMANUALANALOGSCAN,
		FC_DEACTIVATEMANUALANALOGSCAN,
		FC_STARTMANUALSCAN,
		FC_STOPMANUALSCAN,
		FC_PAUSEMANUALSCAN,
		FC_RESUMEMANUALSCAN,
		FC_STARTHOMINGCHANNELSEARCH,
		FC_STOPHOMINGCHANNELSEARCH,
		FC_PAUSEHOMINGCHANNELSEARCH,
		FC_RESUMEHOMINGCHANNELSEARCH,
		FC_STARTCLEARSCRAMBLE,
		FC_STOPCLEARSCRAMBLE,
		FC_PAUSECLEARSCRAMBLE,
		FC_RESUMECLEARSCRAMBLE,
		FC_STORESERVICEFORMANUALANALOGSCAN,
	};
};

