
class IProgramSubscriber_FC
{
public:
	enum EFunctionCode_IProgramSubscriber
	{
		FC_SUBSCRIBEPROGRAM = 0 ,
		FC_UNSUBSCRIBEPROGRAM,
		FC_SUBSCRIBEPROGRAMLISTPF,
		FC_SUBSCRIBEPROGRAMLIST,
		FC_UNSUBSCRIBEPROGRAMLIST,
		FC_MONITORINGTYPE,
	};
};

