
class IDsm_FC
{
public:
	enum EFunctionCode_IDsm
	{
		FC_REQUESTATTACH = 0,
		FC_DETACH,
		FC_REQUESTOBJECTLOAD,
		FC_ABORTOBJECTLOAD,
		FC_ADDMONITOR,
		FC_DELETEMONITOR,
		FC_REQUESTOBJECTNAME,
		FC_GETSERVICECONTEXTLIST,
		FC_GETUSERINFOBYTES,
		FC_REQUESTSTREAMOPEN,
		FC_CLOSESTREAM,
		FC_REQUESTSTREAMINFO,
		FC_REQUESTSTREAMTAP,
		FC_REQUESTEVENTLIST,
		FC_SUBSCRIBEEVENT,
		FC_SUBSCRIBEEVENT_2,
		FC_UNSUBSCRIBEEVENT,
		FC_UNSUBSCRIBEEVENT_2,
		FC_APPLICATIONPROFILE
	};
};

