
class IEITRawData_FC
{
public:
	enum EFunctionCode_IEITRawData
	{
		FC_GETRAWEPGDATAUSINGALLOC = 0 ,
		FC_GETRAWEPGDATAUSINGALLOC_2,
		FC_GETRAWEPGDATAUSINGALLOC_3,
		FC_GETRAWEPGDATAUSINGALLOC_4,
	};
};

