
class IServiceGuide_FC
{
public:
	enum EFunctionCode_IServiceGuide
	{
		FC_GETSPLITPROGRAMLIST = 0 ,
		FC_GETPROGRAMLIST,
		FC_GETPROGRAMLIST_2,
		FC_GETPROGRAM,
		FC_GETPROGRAM_4,
		FC_GETPROGRAM_5,
		FC_GETPRESENTPROGRAM,
		FC_GETGENRELIST,
		FC_SWAPPROGRAMS,
		FC_CHECKPROGRAMEXISTS,
		FC_GETBARKERCHANNEL,
		FC_GETSIMULCASTINFO,
		FC_GETPROGRAMLISTBYGENRE,
		FC_CHECKSERVICEINGROUP,
		FC_SETEPGDYNAMICUPDATEEVENTFOCUSRANGE,
		FC_GETPROGRAMLIST_4,
		FC_SAVEPROGRAMDATA,
	};
};

