
class IDataControl_FC
{
public:
	enum EFunctionCode_IDataControl
	{
		FC_GETCAPTIONDATAMODE = 0 ,
		FC_GETDEFAULTCAPTIONSERVICE,
		FC_GETCAPTIONLANGUAGE,
		FC_SETCURRENTTTX,
		FC_GETCURRENTTTX,
		FC_SETCURRENTHYBRIDSBT,
		FC_GETCURRENTHYBRIDSBT,
		FC_GETPREFERREDTTXSUBTITLE,
		FC_GETPREFERREDHYBRIDSBT,
		FC_SETCURRENTISDBTEXT,
		FC_SETCURRENTISDBTEXTSERVICE,
		FC_GETSTCCOUNT,
		FC_GETCURRENTISDBTEXT,
	};
};

