
class ISOSpecControl_FC
{
public:
	enum EFunctionCode_ISOSpecControl
	{
		FC_CHANGEDIGITALSOSPEC = 0 ,
		FC_CHANGEDIGITALSOSPEC_2,
		FC_CHANGEDIGITALSOSPEC_3,
		FC_CHANGEANALOGSOSPEC,
		FC_CHANGEANALOGSOSPEC_2,
		FC_GETBROADCASTER,
		FC_GETDEFAULTBROADCASTER,
		FC_CHECKBROADCASTERSUPPORTED,
	};
};

