
class IServiceDataAux_FC
{
public:
	enum EFunctionCode_IServiceDataAux
	{
		FC_SIZEOFAUDIO = 0 ,
		FC_GETAUDIO,
		FC_SIZEOFAUDIODESCRIPTION,
		FC_GETAUDIODESCRIPTION,
		FC_SIZEOFTTX,
		FC_GETTTX,
		FC_SIZEOFHYBRIDSBT,
		FC_GETHYBRIDSBT,
		FC_GETCOMPONENTBYPID,
		FC_GETCOMPONENTBYTAG,
		FC_GETALLCOMPONENTS,
		FC_CHECKHARDOFHEARINGSBT,
		FC_GETPREFERREDAUDIO,
		FC_SIZEOFISDBTEXT,
		FC_GETISDBTEXT,
		FC_GETPREFERREDHYBRIDSBT,
		FC_RETURNCHANNELACCESSALLOWED,
		FC_INTERACTIVESERVICEALLOWED,
		FC_CHECKAUDIODESCRIPTION,
	};
};

