
class IRatingUtil_FC
{
public:
	enum EFunctionCode_IRatingUtil
	{
		FC_SETUNLOCKEDINFO = 0 ,
		FC_GETTEMPRATINGBLOCKEDFLAG,
		FC_SETTEMPRATINGBLOCKEDFLAG,
		FC_SETTEMPUNBLOCKEDLEVEL,
		FC_GETTEMPUNBLOCKEDLEVEL,
		FC_SETUNBLOCKEDFLAG18,
		FC_SETRESPONDTOCAM,
		FC_FLAGRESPONDTOCAM,
		FC_SETSERVICELOCKED,
		FC_FLAGSERVICELOCKED,
		FC_SETTEMPUNBLOCKEDZIGGOCHILDLOCK,
		FC_FLAGTEMPUNBLOCKEDZIGGOCHILDLOCK,
		FC_SETTEMPRATINGBLOCKEDBYCAMFLAG,
		FC_GETTEMPRATINGBLOCKEDBYCAMFLAG,
		FC_SETUNLOCKEDINFOWHENFACTORYMODE,
		FC_SEND_RATING_CHANGED_FROM_GUIDE,
	};
};

