
class ISatelliteSettings_FC
{
public:
	enum EFunctionCode_ISatelliteSettings
	{
		FC_GETSETTINGS = 0 ,
		FC_SETSETTINGS,
		FC_SETSETTINGS_2,
		FC_SETENABLEPOSITIONER,
		FC_CHECKENABLEPOSITIONER,
		FC_SETDISEQCVERSION,
		FC_GETDISEQCVERSION,
		FC_RESETDISEQCMODE,
		FC_SETTVCOORDINATES,
		FC_GETTVCOORDINATES,
		FC_CALCULATEUSALS,
		FC_SETENABLESATCR,
		FC_CHECKENABLESATCR,
		FC_SETSATCRSLOTNUMBER,
		FC_SETSATCRSLOTFREQUENCY,
		FC_GETSATCRSETTINGS,
		FC_RESET,
		FC_SELECTSATELLITES,
		FC_CHECKSATELLITESELECTED,
		FC_CHECKSATELLITESELECTED_2,
		FC_GETSATCRDETECTSTATUS,
	};
};

