
class IService_FC
{
public:
	enum EFunctionCode_IService
	{
		FC_FINDSERVICELIST = 0 ,
		FC_FINDSERVICE,
		FC_GETSERVICECOUNT,
		FC_UPDATESERVICE,
		FC_UPDATESERVICELIST,
		FC_INSERTSERVICELIST,
		FC_GETFAVORITES,
		FC_UPDATEFAVORITES,
		FC_MOVEFAVORITES,
		FC_COPYSERVICELIST,
		FC_REORDERSERVICELIST,
		FC_DELETESERVICELIST,
		FC_GETPROVIDERLIST,
		FC_GETBOUQUETS,
		FC_GETBOUQUETCOUNT,
		FC_GETBOUQUETNAME,
		FC_GETSERVICEBOUQUETS,
		FC_REORDERDIGITALSERVICES,
		FC_SAVEMEMORYDB,
		FC_SETBANK,
		FC_REMOVEBANK,
		FC_GETBANKS,
		FC_SETCOUNTRIES,
		FC_GETCOUNTRIES,
		FC_SETHOTELGENRE,
		FC_REMOVEHOTELGENRE,
		FC_GETHOTELGENRES,
		FC_RESTORESERVICE,
		FC_RESTORESERVICELIST,
		FC_FETCHFAVORITES,
	};
};

