
class ISourceControl_FC
{
public:
	enum EFunctionCode_ISourceControl
	{
		FC_SETSOURCE = 0 ,
		FC_SETSOURCE_2,
		FC_SETSHMSINKATTRIBUTE,
		FC_DEACTIVATESOURCE,
		FC_GETCURRENTSOURCEINFO,
		FC_GETPREVIOUSSOURCEINFO,
		FC_TVSERVICESTOP,
		FC_GETSOURCESTATE,
		FC_CHECKEXTSOURCEPLUGGED,
		FC_SOURCELOCKSTATUS,
		FC_RESETCURRENTSOURCEINFO,
		FC_LIVETVSHOWREADY,
		FC_LIVETVSHOWCLOSE,
		FC_ISACTIVE,
		FC_GETAVAILABLESOURCES,
		FC_CHECKSOURCESTATUS,
		FC_STARTSOURCEMONITORING,
		FC_STOPSOURCEMONITORING,
		FC_STARTHDMIANALYSIS,
		FC_STOPHDMIANALYSIS,
		FC_PREPARELFDSOUNDONVIDEOCALL,
	};
};

