
class IPipelineUtility_FC
{
public:
	enum EFunctionCode_IPipelineUtility
	{
		FC_GETSTREAMTIME = 0,
		FC_FLAGSTREAMDST = 1,
		FC_CHECKPIPELINEAVAILABLE = 5,
		FC_NOTIFYRECEIVERSTATE = 6,
		FC_REGISTERFORSTATECHANGE = 7,
		FC_UNREGISTERFROMSTATECHANGE = 8,
		FC_GETTIMEOFFSET = 9,
		FC_GETCURRENTTPMSSTATUS,
		FC_GETPIDSETSTATUS,
	};
};

