
class IUtil_FC
{
public:
	enum EFunctionCode_IUtil
	{
		FC_SETDUALTVAVOFF = 0 ,
		FC_SELECTMASTERAUDIO,
		FC_GETMASTERAUDIO,
		FC_SETTVSYSTEMTIME,
		FC_GETTIMEZONEOFFSET,
		FC_GETAUTOCLOCKTYPE,
		FC_CHECKRCNEDITABLE,
		FC_SETRCNEDITABLE,
		FC_GETPREFERREDLANGUAGE,
		FC_GETSERVICEDB,
		FC_REPLACESERVICEDB,
		FC_BACKUP,
		FC_RESTORE,
		FC_SAVEHISTORYTRACE,
		FC_CLEARHISTORYTRACE,
		FC_CHECKSERVICEDELETESUPPORT,
	};
};

