
class IPVREx_FC
{
public:
	enum EFunctionCode_IPVREx
	{
		FC_MAKETHUMBNAILFRAMEFILESTART = 0 ,
		FC_GETTHUMBNAILFRAMEFILEINFO,
		FC_CHECKAVAILABLETUNERTORECORD,
		FC_GETCANDIDATETUNERLIST,
		FC_GETCONFLICTRECORDLISTFORCHANNELCHANGE,
		FC_GETCONFLICTRECORDLISTFORSOURCECHANGE,
		FC_ISFILERECORDEDLOCAL,
	};
};

