
class IChannelData_FC
{
public:
	enum EFunctionCode_IChannelData
	{
		FC_GETDIGITALFREQUENCY = 0 ,
		FC_GETDIGITALCHANNELNUMBER,
		FC_GETDIGITALCHANNELS,
		FC_GETANALOGFREQUENCY,
		FC_GETANALOGCHANNELNUMBER,
		FC_GETANALOGCHANNELS,
		FC_GETALTERNATIVECHANNELS,
		FC_GETNETWORKNAME,
	};
};

